version: '3'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - db
  
  db:
    container_name: 'dbcsp'
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbCSP
      - TZ=America/Sao_Paulo
        